# Generated by Django 5.2.1 on 2025-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='unpaid', max_length=50),
        ),
    ]
