# Generated by Django 5.2.1 on 2025-05-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0003_alter_cart_options_alter_catalog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
